export enum FilmPlaylistEnum {
    // Best
    Top500 = 1,
    Popular,
    BestAboutApocalypse,
    BestBasedByComics,
    BestForKids,
    BestOf2021Year,
    BestAdaptations,
    Blockbusters,
    MustWatch,
    // Genres
    Comedies,
    Horrors,
    Fiction,
    Thrillers,
    Actions,
    Melodramas,
    Detectives,
    Adventures,
    Fantasy,
    Military,
    Historical,
    Dramas,
    Crimes,
    // Thematic
    DigitalReleases,
    Marvel,
    AboutCartoonsForKids,
    AboutCatastrophe,
    AboutComedianActions,
    AboutDance,
    AboutFamilyComedies,
    AboutLove,
    AboutProgrammers,
    AboutRomanticComedies,
    AboutSchool,
    AboutSharks,
    AboutSpace,
    AboutTeenagers,
    AboutVampires,
    AboutZombies,
}
